{
 "title": "Wind Speed",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current Wind State - Perpignan",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT ts AS time, j->'value' AS state \nFROM situation_history_v1  CROSS JOIN lateral json_array_elements ( metadatas ) AS j WHERE j->>'key' = 'state_perpignan' \nAND $__timeFilter(ts)"
    }
   ]
  },
  {
   "title": "Current Wind State - Montpellier",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT ts AS time, j->'value' AS state \nFROM situation_history_v1  CROSS JOIN lateral json_array_elements ( metadatas ) AS j WHERE j->>'key' = 'state_montpellier' \nAND $__timeFilter(ts)"
    }
   ]
  },
  {
   "title": "Current Wind State - Narbonne",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT ts AS time, j->'value' AS state \nFROM situation_history_v1  CROSS JOIN lateral json_array_elements ( metadatas ) AS j WHERE j->>'key' = 'state_narbonne' \nAND $__timeFilter(ts)"
    }
   ]
  },
  {
   "title": "Current Wind State - avg",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT ts AS time, j->'value' AS state \nFROM situation_history_v1  CROSS JOIN lateral json_array_elements ( metadatas ) AS j WHERE j->>'key' = 'state_avg' \nAND $__timeFilter(ts)"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "graph",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT sh.ts as time, \n(SELECT (result->'aggs'->'value'->'value')::INTEGER FROM fact_history_v1 WHERE id = 4 AND ts = (sh.facts_ids->>'4')::timestamptZ) as speed_avg \nFROM situation_history_v1 as sh\nWHERE\n  $__timeFilter(sh.ts)\nORDER BY sh.ts"
    },
    {
     "rawSql": "SELECT sh.ts as time, (SELECT (result->'aggs'->'speed'->'value')::INTEGER FROM fact_history_v1 WHERE id = 1 AND ts = (sh.facts_ids->>'1')::timestamptZ) as speed_perpignan FROM situation_history_v1 as sh\nWHERE\n  $__timeFilter(sh.ts)\nORDER BY sh.ts"
    },
    {
     "rawSql": "SELECT sh.ts as time, (SELECT (result->'aggs'->'speed'->'value')::INTEGER FROM fact_history_v1 WHERE id = 2 AND ts = (sh.facts_ids->>'2')::timestamptZ) as sped_narbonne FROM situation_history_v1 as sh\nWHERE\n  $__timeFilter(sh.ts)\nORDER BY sh.ts"
    },
    {
     "rawSql": "SELECT sh.ts as time, (SELECT (result->'aggs'->'speed'->'value')::INTEGER FROM fact_history_v1 WHERE id = 3 AND ts = (sh.facts_ids->>'3')::timestamptZ) as speed_montpellier FROM situation_history_v1 as sh\nWHERE\n  $__timeFilter(sh.ts)\nORDER BY sh.ts"
    }
   ]
  }
 ]
}